apiVersion: v1
kind: Secret
metadata:
  name: mythos-secrets
type: Opaque
stringData:
  jwt-secret: "replace-with-64-plus-random-chars"
  postgres-password: "replace-with-postgres-password"
  database-url: "postgresql://mythos:replace-with-postgres-password@mythos-postgres:5432/mythos"
  minio-root-user: "replace-with-minio-access-key"
  minio-root-password: "replace-with-minio-secret-key"
