"""Repository intelligence package for Aeitron MVP."""

from src.aeitron.indexing.context_builder import (
    ContextBuilder,
    HybridRAGEngine,
    RAGEvaluationCandidateReport,
    RAGEvaluationGovernance,
    RAGEvaluationReport,
    RAGEvaluationTask,
    RAGLoadReport,
    RAGScalePlan,
    WorkspaceContextBuilder,
    build_rag_scale_plan,
    build_rag_evaluation_candidates,
    load_governed_rag_evaluation,
    run_rag_load_test,
)
from src.aeitron.indexing.repository_indexer import RepositoryIndexer
from src.aeitron.indexing.vector_index import (
    EmbeddingPair,
    EmbeddingPairBuildReport,
    EmbeddingRetrievalMetrics,
    EmbeddingTrainingConfig,
    EmbeddingTrainingReport,
    LocalVectorIndex,
    ScratchCodeEmbeddingModel,
    ScratchEmbeddingConfig,
    VectorBackendConfig,
    VectorIndexCapability,
    VectorSearchReport,
    VectorSearchResult,
    VectorSyncReport,
    build_embedding_pairs,
    create_vector_index,
    evaluate_embedding_model,
    load_embedding_pairs,
    save_scratch_embedding_checkpoint,
    train_scratch_embedding_model,
    vector_capabilities,
)

__all__ = [
    "ContextBuilder",
    "EmbeddingPair",
    "EmbeddingPairBuildReport",
    "EmbeddingRetrievalMetrics",
    "EmbeddingTrainingConfig",
    "EmbeddingTrainingReport",
    "HybridRAGEngine",
    "RAGEvaluationCandidateReport",
    "RAGEvaluationGovernance",
    "RAGEvaluationReport",
    "RAGEvaluationTask",
    "RAGLoadReport",
    "RAGScalePlan",
    "LocalVectorIndex",
    "RepositoryIndexer",
    "ScratchCodeEmbeddingModel",
    "ScratchEmbeddingConfig",
    "VectorBackendConfig",
    "VectorIndexCapability",
    "VectorSearchReport",
    "VectorSearchResult",
    "VectorSyncReport",
    "WorkspaceContextBuilder",
    "build_embedding_pairs",
    "build_rag_evaluation_candidates",
    "build_rag_scale_plan",
    "create_vector_index",
    "evaluate_embedding_model",
    "load_embedding_pairs",
    "load_governed_rag_evaluation",
    "save_scratch_embedding_checkpoint",
    "train_scratch_embedding_model",
    "run_rag_load_test",
    "vector_capabilities",
]

