compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
mixed_precision: bf16
num_machines: 1
num_processes: 1
deepspeed_config:
  deepspeed_config_file: deploy/gpu/deepspeed_zero2.json
  zero3_init_flag: false
use_cpu: false
